FROM ghcr.io/hutchic-org/kong-build-tools-base-images:deb-1.2.39

ENV PATH=$PATH:/kong/bin:/usr/local/openresty/bin/:/usr/local/kong/bin/:/usr/local/openresty/nginx/sbin/
ENV LUA_PATH=/kong/?.lua;/kong/?/init.lua;/root/.luarocks/share/lua/5.1/?.lua;/root/.luarocks/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;./?.lua;/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua
ENV LUA_CPATH=/root/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;./?.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so

RUN groupadd -g 10000 nobody && \
    rm -rf /usr/local/bin/kong && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    ca-certificates \
    make \
    git \
    curl \
    unzip \
    tzdata \
    vim \
    jq \
    httpie \
    iputils-ping \
    net-tools \
    valgrind \
    libc-dev \
    postgresql-client \
    net-tools && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    curl -L https://cpanmin.us | perl - App::cpanminus \
    && cpanm --notest Test::Nginx \
    && cpanm --notest local::lib

COPY --from=kong-build /tmp/build /
COPY --from=kong-build /test /test
COPY test-kong.sh /root/test-kong.sh
COPY kong /kong

RUN mkdir -p /tmp/build && \
    cd /kong && \
    make dev && \
    kong version && \
    kong roar && \
    /test/kong-openssl/test.sh && \
    /test/kong-runtime/test.sh

WORKDIR /kong

CMD ["sh", "-c", "cat /kong/spec/fixtures/hosts >> /etc/hosts; /bin/bash"]
