---
name: Auto update PR's

on:
  push:
    branches:
    - main
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
    - name: Automatically update PR
      uses: adRise/update-pr-branch@v0.7.2
      with:
        token: ${{ secrets.AUTO_MERGE_TOKEN }}
        base: main
        required_approval_count: 0
        require_passed_checks: true
        sort: created
        direction: desc
